'use strict';
const assert = require('node:assert/strict');
assert.ok(process.versions.bun, 'the source import probe must run under Bun');
const childProcess = require('node:child_process');
const {EventEmitter} = require('node:events');
const fs = require('node:fs');
const http = require('node:http');
const https = require('node:https');
const net = require('node:net');
const path = require('node:path');
const os = require('node:os');
const yaml = require('js-yaml');
const load = yaml.load;
const forbid = () => { throw new Error('library import attempted a host side effect'); };
for (const method of ['writeFileSync', 'writeFile', 'mkdirSync', 'mkdir', 'rmSync', 'rm', 'unlinkSync', 'unlink']) {
  fs[method] = forbid;
  if (fs.promises[method]) fs.promises[method] = forbid;
}
for (const method of ['spawn', 'spawnSync', 'exec', 'execSync', 'execFile', 'execFileSync', 'fork']) childProcess[method] = forbid;
net.connect = net.createConnection = http.request = https.request = forbid;
globalThis.fetch = forbid;
const read = fs.readFileSync;
const source = path.resolve(__dirname, '..') + path.sep;
fs.readFileSync = (file, ...args) => {
  if (typeof file !== 'string' || !path.resolve(file).startsWith(source)) forbid();
  return read(file, ...args);
};
os.homedir = os.userInfo = forbid;
process.exit = forbid;
process.argv.push('--version', '--unknown-consumer-option');
const argv = [...process.argv];
const exitCode = process.exitCode;
const listeners = EventEmitter.defaultMaxListeners;
const {createDevtool} = require('@tanaab/devtool');
const runtime = createDevtool({identity: 'consumer'});
assert.equal(runtime.identity, 'consumer');
assert.deepEqual(process.argv, argv);
assert.equal(process.exitCode, exitCode);
assert.equal(EventEmitter.defaultMaxListeners, listeners);
assert.equal(yaml.load, load);
console.log('import stayed inert; consumer continued');
