name: Example Tests
on:
  pull_request:
permissions:
  contents: read
jobs:
  examples:
    name: ${{ matrix.example }} / ${{ matrix.interface }}
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        example:
          - package
          - config
          - appconfig
          - l337
          # - lando # Re-enable after #25.
          - exec
          - isolation
        interface:
          - cli
          - lib
    env:
      LEIA_TEST_HEADER: Testing ${{ fromJSON('{"cli":"CLI","lib":"Library"}')[matrix.interface] }}
      LEIA_TIMEOUT: '300'
    steps:
      - uses: actions/checkout@v7
      - uses: tanaabased/actions/setup-bun@v1
      - run: bun install --frozen-lockfile --ignore-scripts
      - run: bun run lint
      - uses: ./.github/actions/build-dist
      - uses: tanaabased/actions/run-leia@v1
        env:
          NO_COLOR: '1'
          DEVTOOL_DATA_ROOT: ${{ runner.temp }}/devtool/data
          DEVTOOL_CACHE_ROOT: ${{ runner.temp }}/devtool/cache
          DEVTOOL_COMPILED_CLI: ${{ github.workspace }}/dist/devtool
          DEVTOOL_ISOLATE: '1'
        with:
          scenarios: examples/${{ matrix.example }}/README.md
          shell: bash
          retry: 0
          stdin: false
