name: Unit Tests
on:
  pull_request:
permissions:
  contents: read
jobs:
  unit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: tanaabased/actions/setup-bun@v1
      - run: bun install --frozen-lockfile --ignore-scripts
      - run: bun run test:unit
